[server]
headless = true
port = $PORT
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#ffb347"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#ffffff"
font = "sans serif"
