[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#d33682"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[client]
toolbarMode = "minimal"
