name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload landing/
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./landing

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
